# Generated by Django 4.2.2 on 2023-06-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('wordcount', models.CharField(max_length=10)),
                ('clear_memory', models.BooleanField(default=False)),
            ],
        ),
    ]
