# Generated by Django 4.2.2 on 2023-06-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='clear_memory',
        ),
    ]
